project_id = "exjmsrcyoyyspmuoqono"

[functions.gptmaker-webhook]
verify_jwt = false

[functions.categorize-message]
verify_jwt = false

[functions.abacate-pay-pix]
verify_jwt = false

[functions.abacate-pay-check]
verify_jwt = false

[functions.abacate-pay-webhook]
verify_jwt = false
